<a href="https://colab.research.google.com/github/JuliBaCSE/DeepLearning/blob/ANN/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [31]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset
we inport only the data that is relevant for our output value which is in our case all columns starting from column 3

X is our independent input data

y is our on X dependen output data (result if customer leaves or not)

In [32]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [33]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [34]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

####Label Encoding the "Gender" column


since we cannot work with strings like 'female'/'male' we encode it with 0 and 1

the column is column 2

In [35]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [36]:
print()

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


####One Hot Encoding the "Geography" column

Since we also have strings which represents more that 2 different values (in this case France Germany and Spain) we have to use OneHotEncoding in the Geography column

be aware that this will here encode the strings into 1 0 0 or 0 1 0 for the different countries. Therefore we get 3 columns that are placed in the beginning.

In [37]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [38]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling very important
Here we use only fit transform on our training set otherwise we would get some leackage

In [40]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

we use the class Sequential of tensorflow keras

In [41]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

here units represents the amount of neurons in the first hidden layer 

activation represents the activation function where in this case we use the rectifier activation function for our hidden layer

In [42]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [43]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

since our output value has only 1 dimension (1/0) we set units to 1

Side mark: if we would have as output 3 different classes either A B or C we would need units = 3 to get somethiing like 1 0 0 for A ...

Since our output value is binary result => either left or not we can use a sigmoid function with will give us the properbility that someone leaves

In [44]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

for the optimizer we use the adam which is an extension to a stochastic gradient decent

for loss we use binary_crossentropy since our output values is either 0 or 1 

if we would have more than just 0 and 1 we would need a categorical_crossentropy



In [45]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

the training will be performed by putting the input values for training and the output values for training

the batch_size defines the number of baches that get used for comparison at each interation?

epochs defines the number of epochs that get performed to train our model

in the result we can see that the models accuracy converges pretty fast therefore we could assume that we can reduce the number of epochs

In [46]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6540 - accuracy: 0.6889
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4956 - accuracy: 0.7951
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4588 - accuracy: 0.7885
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4283 - accuracy: 0.8166
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4244 - accuracy: 0.8152
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4210 - accuracy: 0.8186
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8254
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4038 - accuracy: 0.8275
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3775 - accuracy: 0.8457
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3734 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

since our result is a probability (we used the sigmoid function) we can convert to a true or false output but saying prob > 0.5

since we transformed our values we also have to do this here

!! we dont want to fit_transform here !!

In [47]:
print(ann.predict(sc.transform([[1,0,0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [48]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

finally we can ouput the Matrix and the accuracy of our Network

[0][0] = the number or correct prediction that the costumer stays

[0][1] = the number of incorrect predicitons that the costumer leaves

[1][0] = the number or incorrect prediction that the costumer stays

[1][1] = the number of correct predicitons that the costumer leaves

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 197  208]]


0.861